version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  # --- Services ---
  - package-ecosystem: "gomod"
    directory: "/services/proxy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/services/reading-sync"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/services/second-brain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/services/system-metrics"
    schedule:
      interval: "weekly"

  # --- Libraries ---
  - package-ecosystem: "gomod"
    directory: "/pkg/brain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/db"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/env"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/logger"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/metrics"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/secrets"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/telemetry"
    schedule:
      interval: "weekly"

  # --- Portal ---
  - package-ecosystem: "gomod"
    directory: "/page"
    schedule:
      interval: "weekly"
