name: Go Lint & Test

on:
  pull_request:
    branches: [main]
    paths:
      - 'proxy/**'
      - 'system-metrics/**'
      - 'page/**'
      - 'pkg/**'
  push:
    branches: [main]
    paths:
      - 'proxy/**'
      - 'system-metrics/**'
      - 'page/**'
      - 'pkg/**'
  
env:
  go-version: '1.25'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ env.go-version }}
          cache-dependency-path: |
            proxy/go.sum
            system-metrics/go.sum
            page/go.sum
            pkg/db/go.sum
            pkg/logger/go.sum
            pkg/secrets/go.sum

      - name: Check gofmt
        run: make go-format && git diff --exit-code

      - name: Run go vet
        run: make go-vet

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ env.go-version }}
          cache-dependency-path: |
            proxy/go.sum
            system-metrics/go.sum
            page/go.sum
            pkg/db/go.sum
            pkg/logger/go.sum
            pkg/secrets/go.sum

      - name: Run tests
        run: make go-test
