name: Go Lint & Test

on:
  pull_request:
    branches: [main]
    paths:
      - 'proxy/**'
      - 'system-metrics/**'
      - 'page/**'
      - 'pkg/**'
  push:
    branches: [main]
    paths:
      - 'proxy/**'
      - 'system-metrics/**'
      - 'page/**'
      - 'pkg/**'
  
env:
  go-version: '1.25'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ env.go-version }}
          cache-dependency-path: "**/go.sum"

      - name: Check gofmt
        run: make _go-format-internal && git diff --exit-code

      - name: Run go vet
        run: make _go-lint-internal

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ env.go-version }}
          cache-dependency-path: "**/go.sum"

      - name: Run tests
        run: make _go-test-internal
